### ISSUE TITLE
Script is not able to get txn I'd because paytm email formet is changed 

### ISSUE THREAD

**Issue by nalin88** [rishavanand/Paytm-Payment-Verification#2]
Hey bro I really appreciate you for making this script but this is not working now because received payment email formet is changed I request you to fix this issue soon 
![screenshot_2018-02-27-22-34-24-566](https://user-images.githubusercontent.com/36907019/36766255-20644002-1c5b-11e8-985b-5979ef47e08e.jpeg)

**Comment by rishavanand** [comment]
@nalin88 the bug has been fixed. Make sure you re-import the new mysql dump.
